"""empty message

Revision ID: a648b2db1bd0
Revises: b5226e238451
Create Date: 2022-05-20 12:01:13.943953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a648b2db1bd0'
down_revision = 'b5226e238451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favourite', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favourite', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favourite', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favourite', 'planet_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
